const pipeline = [
  {title:'Réception',sub:'React · FastAPI',text:'Création de la soumission puis réception binaire par PUT avec contrats fermés.',limit:'Champs inattendus refusés ; 413 au-dessus du quota et 400 si le corps est vide.',icon:'document'},
  {title:'Contrôle',sub:'MIME · magic bytes',text:'Comparaison du type déclaré avec la signature binaire et détection de préfixe PDF suspect.',limit:'Une entrée incohérente, inconnue ou polyglotte est INVALID_INPUT — jamais analysée artificiellement.',icon:'shield'},
  {title:'Preuve',sub:'Original · SHA-256',text:'Conservation atomique byte-for-byte, calcul du hash et enregistrement des clés d’artefacts.',limit:'Un original existant différent n’est jamais écrasé. Un hash ne prouve pas l’authenticité initiale.',icon:'fingerprint'},
  {title:'Orchestration',sub:'SQLite · asyncio.Queue',text:'Persistance locale puis mise en file bornée. Le worker relit et re-hashe avant analyse.',limit:'La queue locale n’est pas durable en cas de crash ; la divergence de hash produit INCONCLUSIVE.',icon:'activity'},
  {title:'Détection',sub:'Familles de preuve',text:'Les spécialistes PDF natif, signature, provenance C2PA, raster et série produisent séparément des faits typés, localisations et limites.',limit:'Trois contrôles issus de la même représentation PDF restent une seule famille ; aucun modèle visuel ACTIVE n’est installé.',icon:'search'},
  {title:'Décision',sub:'Policy v1.5 · humain',text:'La policy combine risque observé et couverture obligatoire, puis présente une action de traitement à l’analyste.',limit:'HIGH_RISK exige deux détecteurs ACTIVE dans deux familles admissibles. SHADOW ne compte jamais et le moteur ne confirme aucune fraude.',icon:'scales'}
];
const tools = [
  ['Python','3.12+','Livré','Runtime commun de l’API, du parsing et de la policy.','N’isole pas seul les parseurs hostiles.','Socle'],
  ['React','19.2.8','Livré','Crée la soumission et présente ensuite le dossier à l’analyste.','N’est pas une frontière d’autorisation.','Entrée'],
  ['FastAPI','0.141.1','Livré','Reçoit le PUT binaire et expose les routes /v1.','Ne garantit ni sécurité objet ni qualité des détecteurs.','API'],
  ['Pydantic v2','2.13.5','Livré','Ferme et valide les contrats d’entrée et de sortie.','Ne vérifie pas la vérité du contenu.','API'],
  ['MIME + magic bytes','interne','Livré','Contrôle la concordance entre type annoncé et octets.','Ne prouve pas que tout le contenu est bénin.','Validation'],
  ['SHA-256','standard','Livré','Empreinte l’original avant toute transformation.','Un hash valide ne prouve pas l’origine.','Preuve'],
  ['LocalArtifactStore','1.0 interne','Livré','Conserve original, aperçu et rapport par écriture atomique.','Filesystem non HA, sans object lock.','Preuve'],
  ['SQLAlchemy async','2.0.52','Livré','Enregistre dossier, état, rapport, feedback et audit.','PostgreSQL reste à valider réellement.','Persistance'],
  ['SQLite + aiosqlite','0.22.1','Livré','Persiste la démo locale dans une base mono-fichier.','Pas de HA ni de gouvernance production.','Persistance'],
  ['asyncio.Queue','Python stdlib','Livré','Place l’UUID dans la file locale bornée du worker.','Jobs perdus si le processus tombe.','Orchestration'],
  ['asyncio.wait_for','Python stdlib','Partiel','Borne le temps d’analyse et retourne INCONCLUSIVE.','Le thread de parsing peut continuer.','Orchestration'],
  ['pypdf — structure','6.16.2','Livré','Inspecte pages, ressources, révisions, polices et images.','Heuristiques incomplètes sur xref et objets actifs.','Détection PDF'],
  ['pypdf — géométrie','6.16.2','Livré','Analyse spans, collisions, overlays et bounding boxes.','Ne voit pas le texte aplati dans une image.','Détection PDF'],
  ['pypdf — peinture','6.16.2','Livré','Analyse l’ordre des opérations et les overlays post-raster.','Interprétation partielle du clipping et des XObjects.','Détection PDF'],
  ['pyHanko','0.37.0','Partiel','Vérifie l’intégrité cryptographique locale des signatures.','Trust store, révocation et eIDAS non validés.','Détection PDF'],
  ['PDFium','4.30.0','Livré','Rend prudemment la première page PDF.','Pas un détecteur de fraude et pas encore sandboxé.','Rendu'],
  ['Pillow','12.3.0','Livré','Décode et borne la branche image ou le rendu dérivé.','Ne sait pas conclure à une retouche ou IA.','Détection image'],
  ['c2pa-python','0.37.10','Livré','Valide localement les manifestes C2PA de l’original et de certains JPEG natifs incorporés, dans un subprocess borné.','Sans manifeste, aucun fait IA n’est inventé ; profils fournisseur, révocation et sandbox production restent bloqués.','Provenance'],
  ['Classifieur IA déclarative','ai_provenance/1.0.0','Livré','Relève des fournisseurs, workflows génératifs et mentions synthétiques dans des champs allowlistés.','Une métadonnée est falsifiable : elle signifie « déclaré », jamais « fournisseur vérifié ».','Provenance'],
  ['ImageHash','4.3.2','Partiel','Calcule le pHash du rendu pour futurs rapprochements.','Pas encore comparé ; collisions possibles.','Rapprochement'],
  ['Policy par familles','document-forensics.v1.5.0','Livré','Sépare risque et couverture ; route aussi les faits de provenance IA vers une revue explicable.','NORMAL et TRUSTED restent inatteignables tant que les couches obligatoires et la preuve positive manquent.','Décision'],
  ['Console analyste','React 19.2.8','Livré','Affiche faits, couverture, limites et feedback humain.','L’humain reste responsable de la conclusion.','Revue'],
  ['Pages canoniques','contrat 1.1.0','Préparé','Prépare toutes les pages en PNG borné et relie chaque dérivé à l’original.','Scaffold testé hors pipeline actif ; aucun appel de la queue vers le sidecar.','Forensique visuelle'],
  ['Sidecar forensique','adaptateur Null','Préparé','Valide un contrat fermé et retourne une abstention lorsque le modèle manque.','Aucun modèle, poids ou dataset visuel n’est installé ; les résultats restent SHADOW.','Forensique visuelle'],
  ['Navigation guidée','pilote local N1','Partiel','Établit une session WebRTC vidéo consentie sur portail synthétique et manifeste des artefacts hashés.','N’atteste ni l’origine du site, ni l’identité, ni la vérité des pixels.','Provenance'],
  ['Docker multi-stage','définition','Préparé','Assemble frontend et runtime Python non-root.','Pas encore une release approuvée.','Déploiement'],
  ['qpdf + ExifTool + veraPDF','candidats audités','Cible','Ajouteraient une seconde vue structurelle, des faits metadata minimisés et un contrôle de conformité.','Non installés ; licences, transitives, isolation et tests restent des gates.','Évolution déterministe'],
  ['DSS / eIDAS','sidecar Java cible','Cible','Ajouterait une seconde validation PAdES, Trusted Lists et qualification.','Non installé ; listes, révocation, approvisionnement et policy de confiance restent à valider.','Évolution signature'],
  ['Tesseract / PaddleOCR','candidats locaux','Cible','Ajouteraient texte visible, layout, champs et bounding boxes multilingues.','Non installés ; qualité à mesurer par langue, canal et type documentaire.','Évolution sémantique'],
  ['OpenCV','candidat','Cible','Ajouterait copy-move, contours, résidus, segmentation et alignement déterministes.','Non installé ; chaque feature doit être évaluée à faux positifs constants.','Évolution visuelle'],
  ['Connecteurs officiels','preuve positive cible','Cible','Ajouteraient une validation directe auprès de la banque, de l’employeur ou d’une source institutionnelle autorisée.','Accès, consentement, minimisation et confiance émetteur restent à gouverner.','Évolution provenance'],
  ['Modèle Mozzeno','poids propres V2','Expérimental','Localiserait collage, inpainting, copy-move et retouches raster sur le domaine belge.','Nécessite corpus autorisé, split anti-fuite, calibration, OOD et corroboration indépendante.','Évolution visuelle'],
  ['Données réelles','validation écrite','Gate','Permettraient l’évaluation après validations formelles.','Interdit sans approbation DPO, Security et Legal.','Gate final']
];
const proofs=[
  ['N0','Fichier envoyé','Octets reçus + hash','faible'],['N1','Partage d’écran','Continuité visuelle mesurée','observée'],['N2','Co-navigation','DOM et événements contrôlés','instrumentée'],['N3','Navigateur géré','Origine, réseau et téléchargement','renforcée'],['N4','Connecteur officiel','Réponse d’un flux authentifié','forte'],['N5','Attestation signée','Artefact lié à l’émetteur','positive']
];
const statusClass=s=>({'Livré':'delivered','Partiel':'partial','Cible':'target','Expérimental':'experimental','Gate':'gate','Préparé':'prepared'}[s]);
const detailEl=document.querySelector('#pipelineDetail');
function showPipeline(i){document.querySelectorAll('.pipe-step').forEach((el,n)=>el.classList.toggle('active',n===i));const p=pipeline[i];detailEl.innerHTML=`<div class="detail-icon"><svg><use href="#${p.icon}"/></svg></div><div><strong>${String(i+1).padStart(2,'0')} · ${p.title}</strong><p>${p.text}</p></div><small>${p.limit}</small>`;}
document.querySelectorAll('.pipe-step').forEach((button,i)=>button.addEventListener('click',()=>showPipeline(i)));showPipeline(0);
const statuses=['Tous','Livré','Partiel','Préparé','Cible','Expérimental','Gate'];let active='Tous';
const filterEl=document.querySelector('#filters');
let revealObserver=null;
statuses.forEach(s=>{const b=document.createElement('button');b.className='filter'+(s==='Tous'?' active':'');b.textContent=s;b.addEventListener('click',()=>{active=s;document.querySelectorAll('.filter').forEach(x=>x.classList.toggle('active',x===b));renderTools()});filterEl.append(b)});
function renderTools(){const q=document.querySelector('#toolSearch').value.trim().toLocaleLowerCase('fr');const list=tools.map((tool,index)=>({tool,index})).filter(({tool:t})=>(active==='Tous'||t[2]===active)&&t.join(' ').toLocaleLowerCase('fr').includes(q));document.querySelector('#resultCount').textContent=`${list.length} brique${list.length>1?'s':''} affichée${list.length>1?'s':''} · ordre séquentiel conservé`;const grid=document.querySelector('#toolGrid');grid.replaceChildren();list.forEach(({tool:t,index},order)=>{const a=document.createElement('article');a.className='tool-card reveal';a.style.setProperty('--reveal-order',String(order%6));a.innerHTML=`<div class="tool-sequence"><b>${String(index+1).padStart(2,'0')}</b><span>${t[5]}</span></div><div class="tool-top"><div><h3>${t[0]}</h3><span class="version-number">${t[1]}</span></div><span class="status ${statusClass(t[2])}">${t[2].toUpperCase()}</span></div><p>${t[3]}</p><button type="button" aria-expanded="false">Voir la limite <span>＋</span></button><p class="tool-limit">${t[4]}</p>`;a.querySelector('button').addEventListener('click',e=>{const open=a.classList.toggle('open');e.currentTarget.setAttribute('aria-expanded',String(open))});grid.append(a);if(revealObserver)revealObserver.observe(a)});}
document.querySelector('#toolSearch').addEventListener('input',renderTools);renderTools();
const ladder=document.querySelector('#proofLadder');proofs.forEach((p,i)=>{const a=document.createElement('article');a.className='proof-level';a.style.setProperty('--height',`${175+i*24}px`);a.innerHTML=`<b>${p[0]}</b><strong>${p[1]}</strong><p>${p[2]}</p><small>Preuve ${p[3]}</small>`;ladder.append(a)});
const sections=[...document.querySelectorAll('main section[id]')];const links=[...document.querySelectorAll('.topbar nav a')];const observer=new IntersectionObserver(entries=>{entries.forEach(e=>{if(e.isIntersecting)links.forEach(a=>a.classList.toggle('active',a.hash===`#${e.target.id}`))})},{rootMargin:'-35% 0px -55%'});sections.forEach(s=>observer.observe(s));
if(!window.matchMedia('(prefers-reduced-motion: reduce)').matches){document.body.classList.add('motion-ready');revealObserver=new IntersectionObserver(entries=>{entries.forEach(entry=>{if(entry.isIntersecting){entry.target.classList.add('is-visible');revealObserver.unobserve(entry.target)}})},{threshold:.08,rootMargin:'0px 0px -28px'});document.querySelectorAll('.section-head,.metrics article,.fraud-principle,.fraud-summary-card,.fraud-toolbar,.fraud-card,.fraud-legend,.fraud-sources,.pipeline,.detail-panel,.capability-card,.truth-banner,.multilayer-banner,.layer-intro,.tool-card,.plane-card,.roadmap-row,.proof-level,.callout,.do-dont article').forEach((element,index)=>{element.classList.add('reveal');element.style.setProperty('--reveal-order',String(index%6));revealObserver.observe(element)})}
const stackMedia=window.matchMedia('(max-width: 700px)');const planeDeck=document.querySelector('.planes');const planeCards=[...document.querySelectorAll('.plane-card')];let stackFrame=0;function updateMobileStack(){stackFrame=0;if(!stackMedia.matches)return;let active=-1;planeCards.forEach((card,index)=>{const stickyTop=Number.parseFloat(getComputedStyle(card).top)||0;if(card.getBoundingClientRect().top<=stickyTop+2)active=index});planeCards.forEach((card,index)=>{card.classList.toggle('is-stack-active',index===active);card.classList.toggle('is-under',index<active)})}function requestStackUpdate(){if(!stackFrame)stackFrame=requestAnimationFrame(updateMobileStack)}function setStackMode(){planeDeck.classList.toggle('stack-deck',stackMedia.matches);planeCards.forEach((card,index)=>{card.style.setProperty('--stack-index',String(index));card.style.setProperty('--stack-layer',String(index+1))});requestStackUpdate()}window.addEventListener('scroll',requestStackUpdate,{passive:true});window.addEventListener('resize',requestStackUpdate,{passive:true});window.visualViewport?.addEventListener('resize',requestStackUpdate,{passive:true});stackMedia.addEventListener('change',setStackMode);setStackMode();
